const Icons = {
  Profile: require('../assets/Images/Profile.png'),
  Email: require('../assets/Images/Message.png'),
  Hide: require('../assets/Images/Hide.png'),
  Down: require('../assets/Images/Down.png'),
  arrow: require('../assets/Images/arrow.png'),
  scan: require('../assets/Images/scan.png'),
  Ring: require('../assets/Images/Ring.png'),
  Rectangle: require('../assets/Images/Rectangle.png'),
  Right: require('../assets/Images/right.png'),
  help: require('../assets/Images/help.png'),
  Mode: require('../assets/Images/Mode.png'),
  perference: require('../assets/Images/Perference.png'),
  Price: require('../assets/Images/Price.png'),
  Security: require('../assets/Images/Security.png'),
  Bell: require('../assets/Images/Bell.png'),
  toggle: require('../assets/Images/toggle.png'),
  Leftarrow: require('../assets/Images/leftArrow.png'),
  above: require('../assets/Images/above.png'),
  Lock: require('../assets/Images/Lock.png'),
  largeLock: require('../assets/Images/largeLock.png'),
  up: require('../assets/Images/up.png'),
  bitCoin: require('../assets/Images/bitCoin.png'),
  bitIcon: require('../assets/Images/bitIcon.png'),
  upBold: require('../assets/Images/upBold.png'),
  downBold: require('../assets/Images/downBold.png'),
  nft: require('../assets/Images/nft.png'),
  loan: require('../assets/Images/loan.png'),
  eye: require('../assets/Images/eye.png'),
  send: require('../assets/Images/send.png'),
  receiveIcon: require('../assets/Images/receiveIcon.png'),
};
export default Icons;
