const Images = {
  logo: require('../assets/Images/logo.png'),
  alert: require('../assets/Images/danger.png'),
  bitCoin: require('../assets/Images/Group519.png'),
  QRCode: require('../assets/Images/QRcode.png'),
  refresh: require('../assets/Images/refresh1.png'),
  arrow: require('../assets/Images/Vector.png'),
  scanner: require('../assets/Images/Group690.png'),
  Down: require('../assets/Images/Down.png'),
  graph: require('../assets/Images/graph.png'),
  portfolio: require('../assets/Images/portfolioIcon.png'),
  trade: require('../assets/Images/tradeIcon.png'),
  setting: require('../assets/Images/settingIcon.png'),
  more: require('../assets/Images/more.png'),
  coin: require('../assets/Images/image26.png'),
  ETH: require('../assets/Images/ETHicon.png'),
  greenBit: require('../assets/Images/greenBit.png'),
  liteCoin: require('../assets/Images/liteCoin.png'),
  polygon: require('../assets/Images/polygon.png'),
  smartChain: require('../assets/Images/smartChain.png'),
  left: require('../assets/Images/left.png'),
  loan: require('../assets/Images/loan.png'),
  greenLock: require('../assets/Images/greenLock.png'),
  check: require('../assets/Images/Group47.png'),
  splashIcon: require('../assets/Images/splashIcon.png'),
  Doge: require('../assets/Images/Doge.png'),
  copyIcon: require('../assets/Images/copyIcon.png'),
  upload: require('../assets/Images/upload.png'),
  profilePic: require('../assets/Images/profilePic.png'),
  Shield: require('../assets/Images/Shield.png'),
  Wallet: require('../assets/Images/Wallet.png'),
  ArrowDown: require('../assets/Images/ArrowDown.png'),
  orders: require('../assets/Images/orders.png'),
  plus: require('../assets/Images/plus.png'),
  minus: require('../assets/Images/minus.png'),
  yellowLine: require('../assets/Images/yellowLine.png'),
  QRAddress: require('../assets/Images/QRAddress.png'),
  upDown: require('../assets/Images/upDown.png'),
  upload2: require('../assets/Images/Upload2.png'),
};

export default Images;